services:
  web:
    container_name: odoo-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        ODOO_VERSION: ${ODOO_VERSION:-19.0}
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
      - "5678:5678"
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    command: odoo --dev=xml,reload,qweb,sql,werkzeug
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./odoo_core:/opt/odoo/odoo_core:ro
    restart: unless-stopped

  db:
    container_name: odoo-db-dev
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
